Sort the masterclass sessions by date
canonical-web-and-design/webteam.canonical.com pull request #108
Opened 2022-05-15 09:09 UTC by anthonydillon

## Done
Record the datetime object in the dataset and sort by before passing to the template.

## QA
- Go to /masterclasses
- Check the sessions are in order of the newest

2022-05-17 13:59 UTC, sowasred2012 requested changes
One change to make, but everything else looks good

2022-05-17 13:59 UTC, sowasred2012 commented on templates/shared/_card--masterclass.html
> +    by {{ session.Owner }} on {{ <session class="Date Formatted"></session> }}
Looks like autofill got a bit out of line:
```suggestion
    by {{ session.Owner }} on {{ session.Date.Formatted }}
```

2022-05-17 20:43 UTC, anthonydillon commented
Good spot, commited

2022-05-18 08:10 UTC, sowasred2012 approved these changes
LGTM

2022-05-18 20:37 UTC, merged