Improve the masterclasses page
canonical-web-and-design/webteam.canonical.com pull request #109
Opened 2022-05-15 13:22 UTC by anthonydillon

## Done
- Updated the site's navigation
- Pulled the upcoming sessions from the sheet
- Updated the masterclasses template to include upcoming list and information about signing up

## QA
- Open /masterclasses
- Check it looks ok
- Check the information presented matches the [data source](https://docs.google.com/spreadsheets/d/1fFumFWIM3oHwLr9pcBlaANcadAU0bNJxbkfGKwC_1pg/edit#gid=0)

2022-05-17 14:09 UTC, sowasred2012 requested changes
One heading level tweak - also, I'm not sure why but none of the thumbnails are rendering for me? It's not specific to this PR, I also saw it on #108

![image](https://user-images.githubusercontent.com/2376968/168830763-7078f4c8-ea97-44c6-a9b9-ede96825cd9f.png)

2022-05-17 14:09 UTC, sowasred2012 commented on templates/shared/_card--masterclass.html
> +    <h5 class="u-no-margin--bottom"><a href="{{ session.Recording }}">{{ session.Topic }}</a></h5>
There's a jump from heading level 2 to 5 here
```suggestion
    <h3 class="p-heading--5 u-no-margin--bottom"><a href="{{ session.Recording }}">{{ session.Topic }}</a></h3>
```

2022-05-17 14:09 UTC, sowasred2012 commented on templates/shared/_card--masterclass.html
> +    <h5 class="u-no-margin--bottom">{{ session.Topic }}</h5>
```suggestion
    <h3 class="p-heading--5 u-no-margin--bottom">{{ session.Topic }}</h3>
```

2022-05-17 20:06 UTC, anthonydillon commented
Thanks, @sowasred2012 I have addressed your comments and added a default image if the image from google fails. I believe your Google session might have run out or you are missing some permissions to the video directory. If that is the case I need to open the directory to everyone.

2022-05-18 08:09 UTC, sowasred2012 approved these changes
Nice! Looks good to me - I'm pretty sure my Google session is still active, I don't have issues with gmail, calendar, drive etc, so maybe it is permissions? The default image works though.

2022-05-18 09:04 UTC, merged